<Project>
	<PropertyGroup>
		<NamespacePrefix>Purview.Build</NamespacePrefix>
		<RepositoryUrl>https://github.com/purview-dev/build</RepositoryUrl>
		<ExcludePurviewTelemetry>true</ExcludePurviewTelemetry>
	</PropertyGroup>

	<Import Sdk="Purview.BuildSdk" Project="Sdk.props" />

	<PropertyGroup Label="Purview site URL metadata">
		<PurviewHomepage>https://purview.dev/</PurviewHomepage>
		<PurviewProjectUrl>$(PurviewHomepage)projects/build/</PurviewProjectUrl>
		<PurviewDocsUrl>$(PurviewHomepage)docs/build/</PurviewDocsUrl>
	</PropertyGroup>

	<PropertyGroup Label="NuGet package metadata">
		<Authors>Purview Contributors</Authors>
		<Company>Purview Developers</Company>
		<PackageProjectUrl>$(PurviewProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageIcon>purview-logo-light.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup Label="NuGet package assets" Condition="'$(IsPackable)' == 'true'">
		<None Include="$(MSBuildThisFileDirectory)/../README.md" Link="Sdk/README.md" />
		<None Include="$(MSBuildThisFileDirectory)/../LICENSE.md" Link="Sdk/LICENSE.md" />
		<None
			Include="$(MSBuildThisFileDirectory)/../assets/images/purview-logo-light.png"
			Link="Sdk/purview-logo-light.png"
		/>
	</ItemGroup>
</Project>
